---
- name: Validate Network State and Compliance
  hosts: routers
  gather_facts: false
  connection: ansible.netcommon.network_cli

  vars:
    ntp_server: 130.126.24.24

  tasks:
    - name: 1. CHECK OSPF NEIGHBORS (Cisco IOS)
      when: "'cisco' in group_names"
      cisco.ios.ios_command:
        commands:
          - show ip ospf neighbor
      register: r_ospf_neighbors

    - name: 1. CHECK OSPF NEIGHBORS (Arista EOS)
      when: "'arista' in group_names"
      arista.eos.eos_command:
        commands:
          - show ip ospf neighbor
      register: r_ospf_neighbors

    - name: 1. VALIDATE OSPF NEIGHBORS (Cisco/Arista)
      when: r_ospf_neighbors.stdout is defined
      ansible.builtin.assert:
        that:
          - "'FULL' in r_ospf_neighbors.stdout[0]"
        fail_msg: "An OSPF neighbor is not FULL on {{ inventory_hostname }}!"
        success_msg: "OSPF neighbors are FULL on {{ inventory_hostname }}."

    - name: 1. CHECK OSPF NEIGHBORS (Juniper)
      when: ansible_network_os == 'junipernetworks.junos.junos'
      junipernetworks.junos.junos_command:
        commands:
          - show ospf neighbor
      register: r_junos_ospf_neighbors

    - name: 1. VALIDATE OSPF NEIGHBORS (Juniper)
      when: r_junos_ospf_neighbors.stdout is defined
      ansible.builtin.assert:
        that:
          - "'Full' in r_junos_ospf_neighbors.stdout[0]"
        fail_msg: "An OSPF neighbor is not Full on {{ inventory_hostname }}!"
        success_msg: "OSPF neighbors are Full on {{ inventory_hostname }}."

    - name: 2. CHECK ROUTE on R1
      when: inventory_hostname == 'r1'
      cisco.ios.ios_command:
        commands:
          - "show ip route {{ hostvars['r3'].loopback_ip | ansible.utils.ipaddr('address') }}"
      register: r_r1_route

    - name: 2. VALIDATE ROUTE on R1
      when: inventory_hostname == 'r1'
      ansible.builtin.assert:
        that:
          - ("via " ~ (hostvars['r2'].interfaces[0].ip | ansible.utils.ipaddr('address'))) in r_r1_route.stdout[0]
        fail_msg: "Route from R1 to R3 loopback is incorrect!"
        success_msg: "Route from R1 to R3 loopback is correct."

    - name: 3. CHECK NTP COMPLIANCE (Cisco)
      cisco.ios.ios_command:
        commands:
          - show running-config | include ntp
      when: "'cisco' in group_names"
      register: r_ntp_config

    - name: 3. CHECK NTP COMPLIANCE (Arista)
      arista.eos.eos_command:
        commands:
          - show running-config | include ntp
      when: "'arista' in group_names"
      register: r_ntp_config

    - name: 3. CHECK NTP COMPLIANCE (Juniper)
      junipernetworks.junos.junos_command:
        commands:
          - show configuration system ntp
      when: ansible_network_os == 'junipernetworks.junos.junos'
      register: r_ntp_config_junos

    - name: 3. VALIDATE NTP COMPLIANCE
      ansible.builtin.assert:
        that:
          - "ntp_server in (r_ntp_config.stdout[0] | default('')) or ntp_server in (r_ntp_config_junos.stdout[0] | default(''))"
        fail_msg: "NTP server {{ ntp_server }} is not configured on {{ inventory_hostname }}!"
        success_msg: "NTP server is correctly configured on {{ inventory_hostname }}."
